# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
jobs:
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync ./dist/ s3://circle-ci-s3-deploy --delete
