# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: defaulut
      - run: echo "Run your code here"
    
