jobs:
  run:
    description: |
      Describes a welcome message, common environment variables, and documentation links used to get started with CircleCI.
    executor: docker
    steps:
    - run:
        command: welcome_message.sh
        name: Congratulations!
    - run:
        command: next_steps.sh
        name: Next Steps
    - run:
        command: examples.sh
        name: 'Help Topic: Examples - Tutorials, Sample Configs, Cookbook'
    - run:
        command: concepts.sh
        name: 'Help Topic: Overview and Concepts'
    - run:
        command: using_the_cli.sh
        name: 'Help Topic: Using the CLI'
